### PR TITLE
Replace Travis CI with GitHub Actions

### PR DESCRIPTION
**Pull request by fepegar**
I got this to work in my fork. You might need to enable permissions for GitHub Actions being triggered by external PRs in the settings of this repo.

The actions are a bit different to what was happening on Travis, please let me know whether this is close enough or more is needed.

For reference, this is the successful action: https://github.com/fepegar/XCLThesisTemplate/actions/runs/1428772459

### CODE REVIEW

**Comment by fepegar** [comment]
The same or very similar file could also be used for
- https://github.com/MIDL-Conference/MIDLLatexTemplate/issues/15

**Comment by tvercaut** [comment]
I now realise that the miktex build got lost in translation. @fepegar: Did you encounter an issue with porting it to GitHub actions?
https://github.com/cai4cai/XCLThesisTemplate/blob/51c0b356ce51a7e02ce1f2c6f74afff06e7899b3/.travis.yml#L30-L37

**Comment by fepegar** [comment]
I wasn't sure whether it was needed, that's why I said

> The actions are a bit different to what was happening on Travis, please let me know whether this is close enough or more is needed.

Is miktex popular and that's why CI for it is also needed?

**Comment by tvercaut** [comment]
At least back in the days, miktex was the go-to latex distribution on windows. Not sure if things have changed as I haven't worked with windows for many years

**Comment by fepegar** [comment]
Unfortunately, I'm not familiar with Docker, so I'm not sure how to create a clean GHA that uses `miktex/miktex` to build the document.

**Comment by tvercaut** [comment]
Would it be easier (in terms of creating a clean GHA) to install miktex on windows directly without pulling the docker?
https://miktex.org/howto/deploy-miktex

**Pull request merged**
