### PR TITLE
Add job to build the document on Windows using MiKTeX

### PR DESCRIPTION
**Pull request by fepegar**

### CODE REVIEW

**Comment by tvercaut** [comment]
This may help setting up miktex properly from scratch on GHA:
https://github.com/actions/virtual-environments/issues/894#issuecomment-865145384
https://github.com/NREL/EnergyPlus/blob/develop/.github/workflows/documentation-windows.yml

**Comment by fepegar** [comment]
After [many failures](https://github.com/fepegar/XCLThesisTemplate/actions), I tried the workflow from your link and it seemed to work. The YAML is not very elegant, though.

**Comment by tvercaut** [comment]
Thanks for the effort!

Would it still work if the "Download MiKTeX installer" step is split in 2?
1. The actual miktex installation process
2. The latexmk command

**Comment by fepegar** [comment]
Yes, I'll try to clean it up a bit. I was going to mark this PR as Draft, but I guess the option is disabled.

**Comment by fepegar** [comment]
It should be tidier now. I'm still a bit confused a bit the use of quotes and some steps might be redundant, though.

**Comment by tvercaut** [comment]
Super, many thanks!

**Comment by fepegar** [comment]
No worries, thank you for sharing the repo and reviewing the PRs.

**Pull request merged**
